Update newbash

diff --git a/bin/newbash b/bin/newbash
--- a/bin/newbash
+++ b/bin/newbash
@@ -11,5 +11,6 @@ fi
 touch $1
 chmod +x $1
 echo "#!/usr/bin/env bash" >> $1
+echo "set -euo pipefail" >> $1
 
 vim $1
